[backend]
precision              = single
collect-wait-times     = true

[backend-cuda]
device-id = 0

[backend-hip]
device-id = 0

[solver]
system = euler
order  = 1

[solver-time-integrator]
scheme     = euler
controller = none
tstart     = 0
tend       = 0.0002
dt         = 0.0001

[soln-plugin-writer]
dt-out          = 0.0001
basedir         = .
basename        = plugin-lb
async-timeout   = 0

;region IC and BC

[constants]
gamma = 1.4
mu    = 7.395099728874521e-05
Pr    = 0.71
M     = 0.1

[solver-interfaces]
riemann-solver = rusanov
ldg-beta       = 0.5
ldg-tau        = 0.1

[solver-interfaces-line]
flux-pts = gauss-legendre

[solver-elements-quad]
soln-pts = gauss-legendre

[solver-elements-tri]
soln-pts = williams-shunn

[soln-bcs-left]
type = slp-adia-wall


[soln-bcs-right]
type = slp-adia-wall

[soln-bcs-top]
type = slp-adia-wall

[soln-bcs-bottom]
type = slp-adia-wall



[soln-ics]
u   = 1
v   = 0
p   = 1
rho = 1

;endregion

; [soln-plugin-ascent-mesh]
; nsteps        = 1 
; division      = 1     
; region        = *     
; vtkm-backend  = serial
; 
; scene-mesh = {"type"   : "mesh", "render-1": {"image-name"  : "mesh",
;                                               "image-width" : 256, "image-height": 256}}

[soln-plugin-ascent-partition]
nsteps        = 1 
division      = 1     
region        = *     
vtkm-backend  = serial

scene-part = {"type"   : "pseudocolor", "field" : "partition",
              "options": {"mesh": {"show"       : True,
                                   "color"      : [0,0,0],
                                   "line-width" : 1}
              },
              "render-1": {"image-name"  : "ascents/partition",
                           "image-width" : 512, "image-height": 512}}

; python3 ./overlay.py


