[backend]
precision              = single
collect-wait-times     = true

[backend-cuda]
device-id = 0

[backend-hip]
device-id = 0

[solver]
system = euler ; navier-stokes
order  = 1

[solver-time-integrator]
scheme     = euler
controller = none
tstart     = 0
tend       = 2.0000
dt         = 0.0001

[soln-plugin-writer]
dt-out          = 1
basedir         = .
basename        = plugin-lb
async-timeout   = 0

;region IC and BC

[constants]
gamma = 1.4
mu    = 7.395099728874521e-05
Pr    = 0.71
M     = 0.1

[solver-interfaces]
riemann-solver = rusanov
ldg-beta       = 0.5
ldg-tau        = 0.1

[solver-interfaces-line]
flux-pts = gauss-legendre

[solver-elements-quad]
soln-pts = gauss-legendre

[solver-elements-tri]
soln-pts = williams-shunn

[soln-ics]
u   = 1
v   = 0
p   = 1
rho = 1

;endregion